# Generated by Django 5.2.7 on 2025-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do responsável')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('numero_pessoas', models.PositiveIntegerField(default=1, verbose_name='Número de pessoas')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda mensal (R$)')),
                ('recebe_programas_sociais', models.BooleanField(default=False, verbose_name='Recebe programas sociais?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
                ('recebeu_ano_mes', models.CharField(blank=True, help_text='Use formato 2025-10 para registrar mês/ano da última entrega', max_length=7, verbose_name='Recebeu em (AAAA-MM)')),
            ],
        ),
    ]
